apiVersion: apps/v1
kind: Deployment 
metadata: 
    name: model 
    namespace: {{ .Values.ai_model.namespace }} 

spec:
    replicas: 5
    selector:
        matchLabels:
            app: model
    template:
        metadata: 
            labels:
                app: model 
        
        spec:
            containers:
                - name: model 
                  image: {{ .Values.ai_model.image.repository }}
                  imagePullPolicy: {{ .Values.ai_model.image.pullPolicy}}
                  env:
                  - name: BROKER_HOST
                    value: "rabbitml-rabbitmq.rabbit.svc.cluster.local"
                  - name: BROKER_PORT
                    value: "5672"
                  - name: BROKER_USERNAME
                    value: "user"
                  - name: BROKER_PASSWORD
                    value: "passwd"